/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pakkutsppu;

import javax.swing.JFrame;

/**
 *
 * @author PAKKUTSPPU
 */
public class MyCalculator extends javax.swing.JPanel {
    
    static double a=0,b=0,result=0,radian=0;
    static int operator=0;
    static boolean checkEqualPressed = false;

    /**
     * Creates new form MyCalculator
     */
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForMyCalculator = new javax.swing.JPanel();
        buttonForSeven = new javax.swing.JButton();
        buttonForFour = new javax.swing.JButton();
        buttonForFive = new javax.swing.JButton();
        buttonForTwo = new javax.swing.JButton();
        buttonForEight = new javax.swing.JButton();
        buttonForSix = new javax.swing.JButton();
        buttonForNine = new javax.swing.JButton();
        buttonForThree = new javax.swing.JButton();
        buttonForDot = new javax.swing.JButton();
        buttonForRent = new javax.swing.JButton();
        buttonForPlus = new javax.swing.JButton();
        buttonForOne = new javax.swing.JButton();
        buttonForMultiply = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        buttonForMinus = new javax.swing.JButton();
        buttonForEqualsto = new javax.swing.JButton();
        textfieldForInput = new javax.swing.JTextField();
        buttonForZero = new javax.swing.JButton();
        toggleBtnForSwitch = new javax.swing.JToggleButton();
        buttonForSquare = new javax.swing.JButton();
        buttonForSquareRoot = new javax.swing.JButton();
        buttonForPower = new javax.swing.JButton();
        buttonForClear = new javax.swing.JButton();
        labelMyCalculator = new javax.swing.JLabel();
        labelForResult = new javax.swing.JLabel();

        panelForMyCalculator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonForSeven.setText("7");
        buttonForSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForSevenActionPerformed(evt);
            }
        });

        buttonForFour.setText("4");
        buttonForFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForFourActionPerformed(evt);
            }
        });

        buttonForFive.setText("5");
        buttonForFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForFiveActionPerformed(evt);
            }
        });

        buttonForTwo.setText("2");
        buttonForTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForTwoActionPerformed(evt);
            }
        });

        buttonForEight.setText("8");
        buttonForEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForEightActionPerformed(evt);
            }
        });

        buttonForSix.setText("6");
        buttonForSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForSixActionPerformed(evt);
            }
        });

        buttonForNine.setText("9");
        buttonForNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForNineActionPerformed(evt);
            }
        });

        buttonForThree.setText("3");
        buttonForThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForThreeActionPerformed(evt);
            }
        });

        buttonForDot.setText(".");
        buttonForDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForDotActionPerformed(evt);
            }
        });

        buttonForRent.setText("@");

        buttonForPlus.setText("+");
        buttonForPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForPlusActionPerformed(evt);
            }
        });

        buttonForOne.setText("1");
        buttonForOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForOneActionPerformed(evt);
            }
        });

        buttonForMultiply.setText("X");
        buttonForMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForMultiplyActionPerformed(evt);
            }
        });

        jButton16.setText("/");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        buttonForMinus.setText("-");
        buttonForMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForMinusActionPerformed(evt);
            }
        });

        buttonForEqualsto.setText("=");
        buttonForEqualsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForEqualstoActionPerformed(evt);
            }
        });

        buttonForZero.setText("0");
        buttonForZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForZeroActionPerformed(evt);
            }
        });

        toggleBtnForSwitch.setText("O");
        toggleBtnForSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtnForSwitchActionPerformed(evt);
            }
        });

        buttonForSquare.setText("Square");
        buttonForSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForSquareActionPerformed(evt);
            }
        });

        buttonForSquareRoot.setText("sqrt");
        buttonForSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForSquareRootActionPerformed(evt);
            }
        });

        buttonForPower.setText("power^");
        buttonForPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForPowerActionPerformed(evt);
            }
        });

        buttonForClear.setText("Clear");
        buttonForClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForClearActionPerformed(evt);
            }
        });

        labelMyCalculator.setText("My Calculator");

        javax.swing.GroupLayout panelForMyCalculatorLayout = new javax.swing.GroupLayout(panelForMyCalculator);
        panelForMyCalculator.setLayout(panelForMyCalculatorLayout);
        panelForMyCalculatorLayout.setHorizontalGroup(
            panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                                                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buttonForSeven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(buttonForFour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(buttonForEight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(buttonForFive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                                                .addComponent(buttonForOne, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonForTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buttonForThree, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(buttonForNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttonForSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(3, 3, 3)
                                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonForZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(buttonForPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                .addComponent(buttonForDot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                                        .addComponent(buttonForSquare, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonForSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonForPower, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)
                                        .addComponent(buttonForClear, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                                .addGap(2, 2, 2))
                            .addComponent(textfieldForInput))
                        .addGap(8, 8, 8)
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonForRent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForEqualsto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonForMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toggleBtnForSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMyCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelForResult, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelForMyCalculatorLayout.setVerticalGroup(
            panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForMyCalculatorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelMyCalculator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldForInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleBtnForSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelForResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                        .addComponent(buttonForRent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonForMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForEqualsto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelForMyCalculatorLayout.createSequentialGroup()
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonForSquare)
                            .addComponent(buttonForSquareRoot)
                            .addComponent(buttonForPower)
                            .addComponent(buttonForClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonForTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForThree, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForOne, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForZero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonForFour, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForFive, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForSix, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForDot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelForMyCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonForSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForEight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForNine, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonForPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForMyCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForMyCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonForFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForFourActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("4"));
    }//GEN-LAST:event_buttonForFourActionPerformed

    private void buttonForOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForOneActionPerformed
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("1"));
    }//GEN-LAST:event_buttonForOneActionPerformed

    private void buttonForTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForTwoActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("2"));
    }//GEN-LAST:event_buttonForTwoActionPerformed

    private void buttonForThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForThreeActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("3"));
    }//GEN-LAST:event_buttonForThreeActionPerformed

    private void buttonForZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForZeroActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("0"));
    }//GEN-LAST:event_buttonForZeroActionPerformed

    private void buttonForDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForDotActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("."));
    }//GEN-LAST:event_buttonForDotActionPerformed

    private void buttonForSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForSixActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("6"));
    }//GEN-LAST:event_buttonForSixActionPerformed

    private void buttonForFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForFiveActionPerformed
        // TODO add your handling code here:
        textfieldForInput.setText(textfieldForInput.getText().concat("5"));
    }//GEN-LAST:event_buttonForFiveActionPerformed

    private void buttonForSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForSevenActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("7"));
    }//GEN-LAST:event_buttonForSevenActionPerformed

    private void buttonForEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForEightActionPerformed
        // TODO add your handling code here:
        textfieldForInput.setText(textfieldForInput.getText().concat("8"));
    }//GEN-LAST:event_buttonForEightActionPerformed

    private void buttonForNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForNineActionPerformed
        // TODO add your handling code here:
        if(checkEqualPressed)
            textfieldForInput.setText("");
        textfieldForInput.setText(textfieldForInput.getText().concat("9"));
    }//GEN-LAST:event_buttonForNineActionPerformed

    private void buttonForPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForPlusActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        operator=1;
        textfieldForInput.setText("");
    }//GEN-LAST:event_buttonForPlusActionPerformed

    private void buttonForMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForMultiplyActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        operator=3;
        textfieldForInput.setText("");
    }//GEN-LAST:event_buttonForMultiplyActionPerformed

    private void buttonForMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForMinusActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        operator=2;
        textfieldForInput.setText("");
    }//GEN-LAST:event_buttonForMinusActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        operator=4;
        textfieldForInput.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void buttonForEqualstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForEqualstoActionPerformed
        // TODO add your handling code here:
        b=Double.parseDouble(textfieldForInput.getText());
        switch(operator){
            case 1:
                   result=a+b;
                 break;
            case 2: result=a-b;
                    break;
        
            case 3: 
                result=a*b;
                    break;
        
            case 4: 
                result=a/b;
                    break;
                
            case 5: 
                result=Math.pow(a, b);
                    break;
              
               
            default: 
                result=Double.parseDouble(textfieldForInput.getText());
                
        }
        textfieldForInput.setText(String.valueOf(result));
        //labelForResult.setText(String.valueOf(result));
        checkEqualPressed=true;
        
    }//GEN-LAST:event_buttonForEqualstoActionPerformed

    private void buttonForClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForClearActionPerformed
        // TODO add your handling code here:
        textfieldForInput.setText("");
        checkEqualPressed=false;
    }//GEN-LAST:event_buttonForClearActionPerformed

    private void buttonForPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForPowerActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        operator=5;
        textfieldForInput.setText("");
    }//GEN-LAST:event_buttonForPowerActionPerformed

    private void buttonForSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForSquareActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        result=Math.pow(a, 2);
        textfieldForInput.setText(String.valueOf(result));
    }//GEN-LAST:event_buttonForSquareActionPerformed

    private void buttonForSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForSquareRootActionPerformed
        // TODO add your handling code here:
        a=Double.parseDouble(textfieldForInput.getText());
        result=Math.sqrt(a);
        textfieldForInput.setText(String.valueOf(result));
    }//GEN-LAST:event_buttonForSquareRootActionPerformed

    private void toggleBtnForSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtnForSwitchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_toggleBtnForSwitchActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame("MyCalculator");
                frame.setContentPane(new MyCalculator().panelForMyCalculator);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForClear;
    private javax.swing.JButton buttonForDot;
    private javax.swing.JButton buttonForEight;
    private javax.swing.JButton buttonForEqualsto;
    private javax.swing.JButton buttonForFive;
    private javax.swing.JButton buttonForFour;
    private javax.swing.JButton buttonForMinus;
    private javax.swing.JButton buttonForMultiply;
    private javax.swing.JButton buttonForNine;
    private javax.swing.JButton buttonForOne;
    private javax.swing.JButton buttonForPlus;
    private javax.swing.JButton buttonForPower;
    private javax.swing.JButton buttonForRent;
    private javax.swing.JButton buttonForSeven;
    private javax.swing.JButton buttonForSix;
    private javax.swing.JButton buttonForSquare;
    private javax.swing.JButton buttonForSquareRoot;
    private javax.swing.JButton buttonForThree;
    private javax.swing.JButton buttonForTwo;
    private javax.swing.JButton buttonForZero;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel labelForResult;
    private javax.swing.JLabel labelMyCalculator;
    private javax.swing.JPanel panelForMyCalculator;
    private javax.swing.JTextField textfieldForInput;
    private javax.swing.JToggleButton toggleBtnForSwitch;
    // End of variables declaration//GEN-END:variables
}
